name: Area Pod Issue Triage

on: workflow_dispatch

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pod: ["adam/david", "buyaa/jose/steve", "akhil/carlos/viktor"]

    steps:
      - name: Area Pod Issue Triage
        uses: docker://ghcr.io/jeffhandley/action-playground/areapod-issuetriage:main
        with:
          pod: "${{ matrix.pod }}"
