name: Area Pod Issue Triage (from source)

on:
  workflow_dispatch:
    inputs:
      issue:
        description: Issue number
        required: true
        type: number

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest

    steps:
      - name: Area Pod Issue Triage
        uses: jeffhandley/action-playground/actions/AreaPod/AreaPod.IssueTriage/source@main
        with:
          issue: ${{ github.event.inputs.issue }}
