name: Area Pod Issue Triage

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: Issue number
        type: number
        required: true

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest

    steps:
      - name: Area Pod Issue Triage
        uses: jeffhandley/action-playground/actions/AreaPod/AreaPod.IssueTriage@main
        with:
          issue: ${{ github.event.inputs.issue_number }}
